### PR TITLE
disable public docker build and publish

### PR DESCRIPTION
**Pull request by zhenglaizhang**

### CODE REVIEW

**Comment by NullMDR** [comment]
Where is the step to publish to our internal registry?

**Comment by zhenglaizhang** [comment]
@NullMDR there is another internal pipeline to publish to internal acr, I have sent you the link

**Comment by NullMDR** [comment]
@zhenglaizhang I would suggest use azure pipeline to do that in the future, maybe by passing parameter with acr endpoint or something. Merge this one though.

**Comment by zhenglaizhang** [comment]
> @zhenglaizhang I would suggest use azure pipeline to do that in the future, maybe by passing parameter with acr endpoint or something. Merge this one though.

@NullMDR yes, agree with you, will come back to this when there is needs  for the public docker image.

**Pull request merged**
