### PR TITLE
fix gc

### PR DESCRIPTION
**Pull request by JackTn**

### CODE REVIEW

**Comment by raych1** [comment]
Bump the package version?

**Comment by JackTn** [comment]
Bump the package version
- class-validator: 0.9.1 => 0.13.2 
- convict: 5.0.0  => 6.2.2  
- helmet: 3.18.0  => 5.0.2
- node-fetch: 2.6.1 => 2.6.7
- swagger-ui-express: 4.1.2 => 4.3.0

**Comment by JackTn** [comment]
[bump version to 0.3.4]

**Review by raych1 — APPROVED** [review]

**Pull request merged**
